# Generated by Django 3.1.7 on 2021-02-21 12:19

import blog.models
import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to=blog.models.get_profile_image_path, validators=[blog.validators.validate_file_extension]),
        ),
    ]
