# Generated by Django 3.1.7 on 2021-02-21 12:19

from django.db import migrations, models
import info.models
import info.validators


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediasource',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='mediasource',
            name='image',
        ),
        migrations.AddField(
            model_name='mediasource',
            name='video',
            field=models.FileField(null=True, upload_to=info.models.get_profile_image_path, validators=[info.validators.validate_file_extension]),
        ),
    ]
